#!/usr/bin/env bash
#环境变量由root/etc/environment和root/etc/profile.d/toolkit.sh控制
cat >root/etc/environment << EOF
DISPLAY=$DISPLAY
WAYLAND_DISPLAY=$WAYLAND_DISPLAY
XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR
DBUS_SESSION_BUS_ADDRESS=$DBUS_SESSION_BUS_ADDRESS

XDG_SESSION_DESKTOP=labwc
XDG_VTNR=1
XDG_SESSION_TYPE=wayland
XDG_SEAT=seat0
XDG_MENU_PREFIX=gnome-
XDG_SESSION_ID=3
XDG_CURRENT_DESKTOP=labwc

NO_AT_BRIDGE=1
LANG=zh_CN.UTF-8
LANGUAGE=zh_CN:zh
LC_ALL=zh_CN.UTF-8
TZ=Asia/Shanghai

QT_AUTO_SCREEN_SCALE_FACTOR=0
QT_QPA_PLATFORMTHEME_QT6=gtk3
QT_QPA_PLATFORMTHEME=gtk3

GDK_BACKEND=wayland
QT_QPA_PLATFORM=wayland
SDL_VIDEODRIVER=wayland
MOZ_ENABLE_WAYLAND=1

GTK_USE_PORTAL=0
EOF